# Generated by Django 5.1.2 on 2024-10-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0, help_text='Telegram id'),
        ),
    ]
