# Generated by Django 5.1.2 on 2024-10-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_rating_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, help_text='Product rating'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.FloatField(default=0, help_text='Rating'),
        ),
    ]
